server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 입맛에 맞게 데이터베이스 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql 보기좋게 출력
        default_batch_fetch_size: 500 # 1:n 컬렉션 조회 성능 최적화 -> 쿼리 where in 절 사용
    show-sql: true
    open-in-view: false # 영속성 컨텍스트 생존을 트랙잭션 범위로 한정

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나의 크기를 10MB 제한
      max-request-size: 100MB #전체 파일 크기합을 100MB 제한

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 바인딩 되는 값 출력 및 조회 결과 출력
    com.app: debug # todo 패키지 수정

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: ENC(5cne9QPEimU/ioH4MfEuOlc3qD6+C/mEhzCJYWbJkRqZXcGp8j/uP+eT9g545nkc)
    secret: ENC(CDrwD+zZhjPMHUhzGlv7AfeR4XsqbOiZDiCjmTjXAiaA1mbBr4UyWLnLRtLqk/+I)

token:
  secret: ENC(hWHOxcc13oF2FlXCFcxevM+DMonwZu8q) # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

jasypt:
  password: ${PASSWORD}